#pragma once

#include <libzr/modules/zr_common.hpp>

enum class ZrTileEntityType {
    FURNACE = 0,
    CHEST = 1,
    TRAPPED_CHEST = 2,
    ENDER_CHEST = 3,
    JUKEBOX = 4,
    DISPENSER = 5,
    DROPPER = 6,
    SIGN = 7,
    HANGING_SIGN = 8,
    MOB_SPAWNER = 9,
    PISTON = 10,
    BREWING_STAND = 11,
    ENCHANTING_TABLE = 12,
    END_PORTAL = 13,
    BEACON = 14,
    SKULL = 15,
    DAYLIGHT_DETECTOR = 16,
    HOPPER = 17,
    COMPARATOR = 18,
    BANNER = 19,
    STRUCTURE_BLOCK = 20,
    END_GATEWAY = 21,
    COMMAND_BLOCK = 22,
    SHULKER_BOX = 23,
    BED = 24,
    CONDUIT = 25,
    BARREL = 26,
    SMOKER = 27,
    BLAST_FURNACE = 28,
    LECTERN = 29,
    BELL = 30,
    JIGSAW = 31,
    CAMPFIRE = 32,
    BEEHIVE = 33,
    SCULK_SENSOR = 34,
    CALIBRATED_SCULK_SENSOR = 35,
    SCULK_CATALYST = 36,
    SCULK_SHRIEKER = 37,
    CHISELED_BOOKSHELF = 38,
    BRUSHABLE_BLOCK = 39,
    DECORATED_POT = 40,
#if PROTOCOL_VERSION > 766 // 1.21+
    CRAFTER = 41,
    TRIAL_SPAWNER = 42,
    VAULT = 43
#endif
};

#define TILE_ENTITIES 41

static const std::map<ZrTileEntityType, std::string> TileEntityTypeRegistry = {
    {ZrTileEntityType::FURNACE, "furnace"},
    {ZrTileEntityType::CHEST, "chest"},
    {ZrTileEntityType::TRAPPED_CHEST, "trapped_chest"},
    {ZrTileEntityType::ENDER_CHEST, "ender_chest"},
    {ZrTileEntityType::JUKEBOX, "jukebox"},
    {ZrTileEntityType::DISPENSER, "dispenser"},
    {ZrTileEntityType::DROPPER, "dropper"},
    {ZrTileEntityType::SIGN, "sign"},
    {ZrTileEntityType::HANGING_SIGN, "hanging_sign"},
    {ZrTileEntityType::MOB_SPAWNER, "mob_spawner"},
    {ZrTileEntityType::PISTON, "piston"},
    {ZrTileEntityType::BREWING_STAND, "brewing_stand"},
    {ZrTileEntityType::ENCHANTING_TABLE, "enchanting_table"},
    {ZrTileEntityType::END_PORTAL, "end_portal"},
    {ZrTileEntityType::BEACON, "beacon"},
    {ZrTileEntityType::SKULL, "skull"},
    {ZrTileEntityType::DAYLIGHT_DETECTOR, "daylight_detector"},
    {ZrTileEntityType::HOPPER, "hopper"},
    {ZrTileEntityType::COMPARATOR, "comparator"},
    {ZrTileEntityType::BANNER, "banner"},
    {ZrTileEntityType::STRUCTURE_BLOCK, "structure_block"},
    {ZrTileEntityType::END_GATEWAY, "end_gateway"},
    {ZrTileEntityType::COMMAND_BLOCK, "command_block"},
    {ZrTileEntityType::SHULKER_BOX, "shulker_box"},
    {ZrTileEntityType::BED, "bed"},
    {ZrTileEntityType::CONDUIT, "conduit"},
    {ZrTileEntityType::BARREL, "barrel"},
    {ZrTileEntityType::SMOKER, "smoker"},
    {ZrTileEntityType::BLAST_FURNACE, "blast_furnace"},
    {ZrTileEntityType::LECTERN, "lectern"},
    {ZrTileEntityType::BELL, "bell"},
    {ZrTileEntityType::JIGSAW, "jigsaw"},
    {ZrTileEntityType::CAMPFIRE, "campfire"},
    {ZrTileEntityType::BEEHIVE, "beehive"},
    {ZrTileEntityType::SCULK_SENSOR, "sculk_sensor"},
    {ZrTileEntityType::CALIBRATED_SCULK_SENSOR, "calibrated_sculk_sensor"},
    {ZrTileEntityType::SCULK_CATALYST, "sculk_catalyst"},
    {ZrTileEntityType::SCULK_SHRIEKER, "sculk_shrieker"},
    {ZrTileEntityType::CHISELED_BOOKSHELF, "chiseled_bookshelf"},
    {ZrTileEntityType::BRUSHABLE_BLOCK, "brushable_block"},
    {ZrTileEntityType::DECORATED_POT, "decorated_pot"},
#if PROTOCOL_VERSION > 766 // 1.21+
    {ZrTileEntityType::CRAFTER, "crafter"},
    {ZrTileEntityType::TRIAL_SPAWNER, "trial_spawner"},
    {ZrTileEntityType::VAULT, "vault"},
#endif
};

static const std::map<std::string, ZrTileEntityType> TileEntityTypeRegistryByName = {
    {"furnace", ZrTileEntityType::FURNACE},
    {"chest", ZrTileEntityType::CHEST},
    {"trapped_chest", ZrTileEntityType::TRAPPED_CHEST},
    {"ender_chest", ZrTileEntityType::ENDER_CHEST},
    {"jukebox", ZrTileEntityType::JUKEBOX},
    {"dispenser", ZrTileEntityType::DISPENSER},
    {"dropper", ZrTileEntityType::DROPPER},
    {"sign", ZrTileEntityType::SIGN},
    {"hanging_sign", ZrTileEntityType::HANGING_SIGN},
    {"mob_spawner", ZrTileEntityType::MOB_SPAWNER},
    {"piston", ZrTileEntityType::PISTON},
    {"brewing_stand", ZrTileEntityType::BREWING_STAND},
    {"enchanting_table", ZrTileEntityType::ENCHANTING_TABLE},
    {"end_portal", ZrTileEntityType::END_PORTAL},
    {"beacon", ZrTileEntityType::BEACON},
    {"skull", ZrTileEntityType::SKULL},
    {"daylight_detector", ZrTileEntityType::DAYLIGHT_DETECTOR},
    {"hopper", ZrTileEntityType::HOPPER},
    {"comparator", ZrTileEntityType::COMPARATOR},
    {"banner", ZrTileEntityType::BANNER},
    {"structure_block", ZrTileEntityType::STRUCTURE_BLOCK},
    {"end_gateway", ZrTileEntityType::END_GATEWAY},
    {"command_block", ZrTileEntityType::COMMAND_BLOCK},
    {"shulker_box", ZrTileEntityType::SHULKER_BOX},
    {"bed", ZrTileEntityType::BED},
    {"conduit", ZrTileEntityType::CONDUIT},
    {"barrel", ZrTileEntityType::BARREL},
    {"smoker", ZrTileEntityType::SMOKER},
    {"blast_furnace", ZrTileEntityType::BLAST_FURNACE},
    {"lectern", ZrTileEntityType::LECTERN},
    {"bell", ZrTileEntityType::BELL},
    {"jigsaw", ZrTileEntityType::JIGSAW},
    {"campfire", ZrTileEntityType::CAMPFIRE},
    {"beehive", ZrTileEntityType::BEEHIVE},
    {"sculk_sensor", ZrTileEntityType::SCULK_SENSOR},
    {"calibrated_sculk_sensor", ZrTileEntityType::CALIBRATED_SCULK_SENSOR},
    {"sculk_catalyst", ZrTileEntityType::SCULK_CATALYST},
    {"sculk_shrieker", ZrTileEntityType::SCULK_SHRIEKER},
    {"chiseled_bookshelf", ZrTileEntityType::CHISELED_BOOKSHELF},
    {"brushable_block", ZrTileEntityType::BRUSHABLE_BLOCK},
    {"decorated_pot", ZrTileEntityType::DECORATED_POT},
#if PROTOCOL_VERSION > 766 // 1.21+
    {"crafter", ZrTileEntityType::CRAFTER},
    {"trial_spawner", ZrTileEntityType::TRIAL_SPAWNER},
    {"vault", ZrTileEntityType::VAULT},
#endif
};

struct ZrTileEntityCounts {
    std::vector<uint16_t> counts;
    time_t timestamp{};
};

typedef std::vector<ZrTileEntityCounts> TileEntities;

std::ostream& operator<<(std::ostream& os, ZrTileEntityType tileEntityType);