#pragma once

enum ZVCRCoreVersion {
    ZVCR_0_0_0_0
};

namespace zvcr::common::definitions {

#if ZVCR_VERSION == ZVCR_0_0_0_0
#define PROTOCOL_VERSION 765
#endif

    constexpr size_t REGION_SIDELENGTH_SEGMENTS = 32;
    constexpr size_t SEGMENTS_PER_REGION = REGION_SIDELENGTH_SEGMENTS * REGION_SIDELENGTH_SEGMENTS;

    constexpr size_t SEGMENT_SIDELENGTH_BLOCKS = 16;
    constexpr size_t SECTION_2D_SIZE_BLOCKS = SEGMENT_SIDELENGTH_BLOCKS * SEGMENT_SIDELENGTH_BLOCKS;
    constexpr size_t SECTION_3D_SIZE_BLOCKS = SEGMENT_SIDELENGTH_BLOCKS * SEGMENT_SIDELENGTH_BLOCKS * SEGMENT_SIDELENGTH_BLOCKS;

}