#pragma once

#include <cstddef>
#include <cstdint>

#define PROTOCOL_VERSION 765

namespace zvcr::common::definitions {

    constexpr size_t REGION_SIDELENGTH_SEGMENTS = 32;
    constexpr size_t SEGMENTS_PER_REGION = REGION_SIDELENGTH_SEGMENTS * REGION_SIDELENGTH_SEGMENTS;

    constexpr size_t SEGMENT_SIDELENGTH_BLOCKS = 16;
    constexpr size_t SECTION_2D_SIZE_BLOCKS = SEGMENT_SIDELENGTH_BLOCKS * SEGMENT_SIDELENGTH_BLOCKS;
    constexpr size_t SECTION_3D_SIZE_BLOCKS = SEGMENT_SIDELENGTH_BLOCKS * SEGMENT_SIDELENGTH_BLOCKS * SEGMENT_SIDELENGTH_BLOCKS;

    constexpr size_t SEGMENT_SIDELENGTH_BIOMES = 4;
    constexpr size_t SECTION_2D_SIZE_BIOMES = SEGMENT_SIDELENGTH_BIOMES * SEGMENT_SIDELENGTH_BIOMES;
    constexpr size_t SECTION_3D_SIZE_BIOMES = SEGMENT_SIDELENGTH_BIOMES * SEGMENT_SIDELENGTH_BIOMES * SEGMENT_SIDELENGTH_BIOMES;

    using BiomeId = uint16_t;

    using BlockStateId = uint16_t;
    using Segment2dAtom = uint16_t;

}